ServerName smartfarm
ServerAdmin admin@smartfarm.com
DocumentRoot /app/smartfarm

<Directory /app/smartfarm>
 AllowOverride All
 Require all granted
</Directory>

ErrorLog /app/error.log
CustomLog /app/access.log combined

